import "./globals.css";
import ProviderLayout from "@/Components/ProviderLayout";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-poppins">
        <ProviderLayout>{children}</ProviderLayout>
      </body>
    </html>
  );
}
